### ISSUE TITLE
Ignore last 5 seconds button

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#10]
Do we implement the following feature (Pierre suggestion)?

While measuring if somebody is disturbed by an event, give him the ability to pause the capture then on resume delete the last 5 records (5 seconds).

**Comment by Picaut** [comment]
Yes, add a "pause/resume" button with deleting x secons (x, as a user parameter)

**Comment by nicolas-f** [comment]
done
