### ISSUE TITLE
Applying correction factor

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseCapture#103]
When manually added in the App settings, the correction factor (I;I;e the gain) seems applied only after restarting the App (or may be reloaded the Measurement activity). This must be fixed.

**Comment by nicolas-f** [comment]
The gain is already applied when the config change https://github.com/Ifsttar/NoiseCapture/blob/0.4.2/app/src/main/java/org/noise_planet/noisecapture/MeasurementActivity.java#L138
