### ISSUE TITLE
Add color in Results activity

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#11]
Add color for LA10, LA50, LA90, Min and Max in result activity.

**Comment by nicolas-f** [comment]
Is it ok ?

![noisecaptureresult](https://cloud.githubusercontent.com/assets/1382241/14918324/960cd8ca-0e23-11e6-9453-e045b5612cd7.png)

**Comment by Picaut** [comment]
Yes, it is.
