### ISSUE TITLE
Add more elements in the History (geoserver)

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseCapture#112]
Increase the number of measurement that are displayed on the webpage, up to 30 for example (10 is not enough). Is-this value can be defined as a user parameters in the 'Settings' webpage?

**Comment by nicolas-f** [comment]
Yes and it could be technically feasible to fetch history by page.

**Comment by nicolas-f** [comment]
```javascript
window.onscroll = function(ev) {
    if ((window.innerHeight + window.pageYOffset) >= document.body.offsetHeight) {
        //currently scrolled at bottom of the page, fetch more content
    }
};
```

**Comment by Picaut** [comment]
- [ ] Replace "Goto image" by the name of country
- [ ] Display "Last week" history
- [ ] Rename "Last measurement" by "Last week"

**Comment by nicolas-f** [comment]
Current state

![image](https://user-images.githubusercontent.com/1382241/29360940-8ec8c164-8285-11e7-911b-5fbbab90bb0e.png)

**Comment by pierromond** [comment]
Are you sure we should put the flags ? I think it can potentially scared the users about privacy, and it doesn't bring any acoustic information.

**Comment by nicolas-f** [comment]
The download size of the history may be too high if we set a time dependent size, if someone spam the uploads.

@pierromond Discussion on path is here #113
