### ISSUE TITLE
Show the corresponding path on a measurement history item

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseCapture#113]
When a measurement is selected in the 'History' web page, displays the start and end points (using the map marker for example), and shows the corresponding path.

**Comment by ebocher** [comment]
Don't understand. Do you want to display the path of the measure ?

**Comment by ebocher** [comment]
If you want to zoom on the last bounding box of a measure you can used
map.fitBounds([[
        32.958984,
        -5.353521
    ], [
        43.50585,
        5.615985
    ]]);

**Comment by nicolas-f** [comment]
When a measurement is selected, the bound box zoom is wrong. The following method must be chosen:

```js
map.fitBounds([[ 32.958984, -5.353521 ], [ 43.50585, 5.615985 ]]);
```
