### ISSUE TITLE
Add automatic calibration from reference devices

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseCapture#114]
Simplify the calibration action by using an automatic process with an automatic connection to reference devices

**Comment by nicolas-f** [comment]
# Communications between Host<->Clients

## Template

`MessageId|param1|param2..`

## Messages

| Id | Description            | Param1              | Param2              |
|----|------------------------|---------------------|---------------------|
| 1  | Ping communication     | CHECK               |                     |
| 2  | Pong communication     | CHECK               |                     |
| 3  | Start calibration      | WarmupTime(ms)      | CalibrationTime(ms) |
| 4  | PeerLeq1s during calib | value(dB)           |                     |
| 5  | PeerCalibrationResult  | leq n seconds(dB)   |                     |
| 6  | HostApply              | Reference level(dB) |                     |
| 7  | Host cancel            |                     |                     |

**Comment by nicolas-f** [comment]
In the measurement properties file, add the name of the reference device.

**Comment by Picaut** [comment]
Done form release 1.2.3, with a great enhancement in release 1.2.7 (best audio communication between smartphones). The method uses a reference smartphone (already calibrated) to calibrate other smartphones, using the ambiant noise or a pink noise. The method is automatic with NoiseCapture.
