### ISSUE TITLE
Public dump of database

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#116]
Idea from @ebocher 

Create a groovy project to build a zip file containing the dump of all tables into shapes files.

This zip file could be downloaded on the server through a public link.

**Comment by ebocher** [comment]
It would be nice to have two zip file : 

- first with the raw measures (points + trace + metadata on columns)
- second with the hexa geometries

These files will be  daily updated.

The files will be available on the webcarto in a new tab : download data

**Comment by nicolas-f** [comment]
Use the extend of the view to build a WPS query to extract raw data.

Raw data is a geojson file that contains:

- Pleasantness
- Tags
- Per second
 - leq
 - position
 - gps precision

**Comment by nicolas-f** [comment]
I'm quite worried about cpu usage of processing such potential amount of data on demand.

I have another solution:

Share the "processed" folder of onomap using apache. (the folder of processed zip files)
Create a wps that return the records UUID for a coordinates bounding box.
On javascript client side of leaflet, build a single archive of the current view using the wps and this js lib https://stuk.github.io/jszip/

This method does not require Groovy on onomap to fetch and process large amount of data.

What do you think @ebocher ? @Picaut

**Comment by ebocher** [comment]
This is not the same information and the same date.
I think it would be better to offer a dump (geojson) build each night . 
The dump could be slitted by country as osm does. On the side menu the user shows a link (URL) to the file.
What do u think ?

**Comment by ebocher** [comment]
Please provide at least a GIS data format. We must think about end-user.

**Comment by nicolas-f** [comment]
@ebocher Yes it is the best solution:

Writing geojson does not require external library under groovy

So I write a restricted access wps process that write on disk the following files:
```
Chile_Valparaíso_Valparaíso.tracks.geojson
Chile_Valparaíso_Valparaíso.measures.geojson
Chile_Valparaíso_Valparaíso.areas.geojson  
France_Bretagne_Finistère.tracks.geojson      
France_Bretagne_Finistère.measures.geojson      
France_Bretagne_Finistère.areas.geojson        
France_Pays de la Loire_Loire-Atlantique.tracks.geojson 
France_Pays de la Loire_Loire-Atlantique.measures.geojson       
France_Pays de la Loire_Loire-Atlantique.areas.geojson       
Germany_Hamburg_Hamburg.tracks.geojson  
Germany_Hamburg_Hamburg.measures.geojson  
Germany_Hamburg_Hamburg.areas.geojson    
Italy_Lazio_Roma.tracks.geojson      
Italy_Lazio_Roma.measures.geojson      
Italy_Lazio_Roma.areas.geojson      
``` 
 - *.tracks.geojson
    - linestring of the tracks
    - pleasantness
    - tags
    - calibration gain
    - record date
    - laeq (x seconds)
    - record length (seconds)
  - *.measures.geojson
    - point
    - precision
    - noise level 1s
  - *.areas.geojson
    - hexagon coordinates
    - noise level LA50 for each hour of week
    - first measure date
    - last measure date

**Comment by nicolas-f** [comment]
Do you think I should GZIP the files ?

**Comment by ebocher** [comment]
linestring of the tracks is not necessary you can store in measures the id of the track

**Comment by ebocher** [comment]
Yes you shoud gzip the file.
Nut I don't understand the " restricted access " ?

**Comment by nicolas-f** [comment]
```Nut I don't understand the " restricted access " ?```

User should not be allowed to trigger the database dump

**Comment by ebocher** [comment]
Is it based on an area ? by country, according a NUTS level ?

**Comment by ebocher** [comment]
User are only able to download the last geojson file dumped each day ?

**Comment by nicolas-f** [comment]
The wps dump process is called one time per day by onomap's system

**Comment by nicolas-f** [comment]
For the time dump.
Is unix timestamp is sufficant ?

Or/and I need also to export using ISO_8601 with measure location specific timezone ?

**Comment by nicolas-f** [comment]
So it was decided to change the final content of folders:

A single .zip file will be created for each country (name_0)

In each zip file the content will be:
```
Chile_Valparaíso_Valparaíso.tracks.geojson
Chile_Valparaíso_Valparaíso.points.geojson
Chile_Valparaíso_Valparaíso.areas.geojson  
France_Bretagne_Finistère.tracks.geojson      
France_Bretagne_Finistère.points.geojson      
France_Bretagne_Finistère.areas.geojson        
France_Pays de la Loire_Loire-Atlantique.tracks.geojson 
France_Pays de la Loire_Loire-Atlantique.points.geojson       
France_Pays de la Loire_Loire-Atlantique.areas.geojson       
Germany_Hamburg_Hamburg.tracks.geojson  
Germany_Hamburg_Hamburg.points.geojson  
Germany_Hamburg_Hamburg.areas.geojson    
Italy_Lazio_Roma.tracks.geojson      
Italy_Lazio_Roma.points.geojson      
Italy_Lazio_Roma.areas.geojson   
```

Is it ok ?

**Comment by gpetit** [comment]
In my Opinion, the time dump should be in ISO_8601.

Ok for one zip per country

**Comment by nicolas-f** [comment]
I have an issue with streams. It don't have to redo all the algorithm if I do that:

```
France.tracks.zip
France.points.zip
France.areas.zip
Germany.tracks.zip
Germany.points.zip
Germany.areas.zip
Italy.tracks.zip
Italy.points.zip
Italy.areas.zip
```

And in France.tracks.zip:

```
France_Bretagne_Finistère.tracks.geojson           
France_Pays de la Loire_Loire-Atlantique.tracks.geojson 
```

@gpetit  @ebocher

**Comment by nicolas-f** [comment]
Forget about it I will search how to do it.

**Comment by nicolas-f** [comment]
For the hexagon dump. Is it really necessary to export the 72 leq levels (hour by hour level day of the week+saturday+sunday)

I try to optimize the Query but it is quite long to fetch 72 values for each hexagon:

```sql
DROP TABLE IF EXISTS dumptest;


CREATE TABLE dumptest AS
SELECT name_0,
       name_1,
       name_2,
       na.the_geom,
       cell_q,
       cell_r,
       tzid,
       mean_leq,
       mean_pleasantness,
       measure_count,
       first_measure,
       last_measure,

  (SELECT string_agg(to_char(leq, '999D9'), '_') leq_profile
   FROM
     (SELECT leq
      FROM noisecapture_area_profile nap
      WHERE nap.pk_area = na.pk_area
      ORDER BY hour) ordered_leq_profile) leq_profile
FROM noisecapture_area na,
     gadm28 ga
WHERE ST_PointOnSurface(na.the_geom) && ga.the_geom
  AND st_intersects(ST_PointOnSurface(na.the_geom),
                    ga.the_geom)
ORDER BY name_0,
         name_1,
         name_2;
```

**Comment by nicolas-f** [comment]
Maybe it's not the subquery the problem. We will optimize or disable the dump of hexagons if it takes too much time.

**Comment by nicolas-f** [comment]
This is the intersection between gadm and hexagon that take time. Maybe gadm polygons are too complex ?

**Comment by nicolas-f** [comment]
This query provide 4x speed-up

```sql
SELECT pk_point,
       the_geom,
       pk_track,
       noise_level,
       speed,
       accuracy,
       orientation,
       time_date,
       time_location
FROM noisecapture_point;


DROP TABLE IF EXISTS dumptest;


CREATE TABLE dumptest AS
SELECT name_0,
       name_1,
       name_2,
       na.the_geom,
       cell_q,
       cell_r,
       tzid,
       mean_leq,
       mean_pleasantness,
       measure_count,
       first_measure,
       last_measure,

  (SELECT string_agg(to_char(leq, 'FM999'), '_') leq_profile
   FROM
     (SELECT leq
      FROM noisecapture_area_profile nap
      WHERE nap.pk_area = na.pk_area
      ORDER BY hour) ordered_leq_profile) leq_profile
FROM noisecapture_area na,
     gadm28 ga
WHERE ST_Centroid(na.the_geom) && ga.the_geom
  AND st_contains(ST_centroid(na.the_geom),
                  ga.the_geom)
ORDER BY name_0,
         name_1,
         name_2;
```

**Comment by nicolas-f** [comment]
It is deployed but not automated yet

What is the sub-domain and domain for the public dump url ?

**Comment by ebocher** [comment]
About the readme.htm you could add

All raw data offered from the NoiseCapture Android App, i.e. the DATABASE-NoiseCaptureRaw, are made available under the Open Database License. Any rights in individual contents of the database are licensed under the Database Contents License.

The data provided  has no legal force and serves for information purposes only. Absolutely no accuracy or completeness guarantee is implied or intended. The authors are not responsible for the direct or indirect consequences of the uses or interpretation of the information provided.

**Comment by ebocher** [comment]
By the way, the readme file must contains also some metadata to describe the geojson files and columns.

**Comment by nicolas-f** [comment]
Description of files:

*.tracks.geojson

Each feature is a measure session of `time_length` seconds. The geometry is the bounding box of measurements locations. 
- `time_ISO8601` start of measurement using ISO8601 time representation
- `time_epoch` start of measurement in unix timestamp format (number of milliseconds since January 1, 1970, 00:00:00 GMT). The timezone is provided by the localization of the measure, not the configuration of the smartphone.
- `pk_track` Database track primary key. This value may change when the zip files are updated but are unique in the same zip file. This value is linked with *.points.geojson
- `track_uuid` Track Universally Unique IDentifier. This unique value never change between zip updates.
- `gain_calibration` Signal gain in dB, provided from user using phone calibration. This signal gain is already applied to all noise levels related to this track.
- `noise_level` Laeq level of the track
- `tags` User supplied tags. Some may be deleted or added later.
- `pleasantness` User supplied pleasantness 0-100

*.points.geojson

Each feature is a measure second. The geometry is the localization of the measure.

- `pk_track` Database track primary key. This value may change when the zip files are updated but are unique in the same zip file. This value is linked with *.tracks.geojson
- `time_ISO8601` Sound level measurement time using ISO8601 time representation
- `time_epoch` Sound level measurement time in unix timestamp format (number of milliseconds since January 1, 1970, 00:00:00 GMT)
 - `time_gps_ISO8601` GPS localization may not be obtained each second. So the provided location is attached to this "gps fix" time.
- `time_gps_epoch` "gps fix" time in unix timestamp format (number of milliseconds since January 1, 1970, 00:00:00 GMT)
- `noise_level` Noise level LAeq in dB(A) 1s
- `speed` GPS provided speed, not accurate.
- `orientation` GPS provided orientation, not accurate.
- `accuracy` GPS localization accuracy in meters. There is a 68% chance that the true location is within that radius of the measured point in meters.

**Comment by ebocher** [comment]
This value is linked with *.points.geojson and could be used to build a geometry representation of the path of the meaures ?

**Comment by ebocher** [comment]
The rest is perfect

**Comment by ebocher** [comment]
Done and the website is up to date.
Please closed
