### ISSUE TITLE
Embed leaflet within application

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseCapture#117]
Embed leaflet within application

**Comment by ebocher** [comment]
We must embedded a light leaflet version with only a layer map controller and few layers.
However it would be nice to add a link : go to the main community map or something similar.

**Comment by nicolas-f** [comment]
What is the better rendering for the measurement points ?

![point_rendering](https://user-images.githubusercontent.com/1382241/28825970-8f54e608-76c8-11e7-9474-d75b5a85d27a.png)

**Comment by Picaut** [comment]
The left one.

**Comment by MatthieuQ** [comment]
The left one
