### ISSUE TITLE
Use of European NUTS or  GADM database to compute indicators

### ISSUE THREAD

**Issue by ebocher** [Ifsttar/NoiseCapture#124]
It would be nice to compute some basic indicators like number of measures at several geographic scales.
We can use : http://ec.europa.eu/eurostat/fr/web/nuts/overview or http://gadm.org/ or http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative

I propose to do a test with the ENERGIC-OD VH that will be able to offer a WFS layer with a geojson profile.

**Comment by ebocher** [comment]
To complete the issue.
The idea is to add a new entry in the sidebar to order country by maximum of contributors and in the future some statics for each country sub levels.

**Comment by nicolas-f** [comment]
Use cached view using this feature  https://www.postgresql.org/docs/9.3/static/rules-materializedviews.html

**Comment by ebocher** [comment]
The GADM has been imported in the main database.
I will work now on a processing to aggregate geometries at country scales.

**Comment by ebocher** [comment]
This groovy script has been used in OrbisGIS  to merge all countries

```java

sql.execute "drop table if exists gadm28_id_0"
sql.execute "create table gadm28_id_0 (the_geom geometry , id_0 integer)"

sql.eachRow("SELECT distinct id_0 from  gadm28 "){ row ->
println row.id_0 
sql.execute "insert into gadm28_id_0 (select st_union(st_accum(the_geom)) as the_geom, id_0 from gadm28 where id_0="
    }
```
I will upload in the database a new table name  gadm28_id_0.

**Comment by ebocher** [comment]
Done
