### ISSUE TITLE
GPS/Network Position problem hint

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#13]
Show an hint to indicate the current status of positioning system such as GPS/Wifi/Antenna Relay

**Comment by nicolas-f** [comment]
Proposition of GUI:
![accur2](https://cloud.githubusercontent.com/assets/1382241/15389233/23911408-1db6-11e6-978f-9fcf4615438f.jpg)

**Comment by nicolas-f** [comment]
Color is changing to green if below 15m precision

**Comment by nicolas-f** [comment]
No GPS hint
![screenshot0](https://cloud.githubusercontent.com/assets/1382241/15389384/e066322a-1db6-11e6-9309-ce902a25c1e2.png)

**Comment by ebocher** [comment]
Sounds good for me
