### ISSUE TITLE
Improve the "calibration" description

### ISSUE THREAD

**Issue by gpetit** [Ifsttar/NoiseCapture#132]
In the website (http://noise-planet.org/en/noisecapture.html or http://noise-planet.org/en/noisecapture_protocol.html) we should improve the description of the calibration.

Right now, we just explain that users should calibrate their smartphones before mesuring, but we don't explain the two possible procedures:
- using a reference device (how it works, who has this kind of device, ... ?),
- using the calibration tool, to do in a room with no noise

With @Picaut we also talked about the possibility to complete with a small video tutorial ... it can be a good idea

In the meantime, we probably also should add a sentence in the "calibration" part of NoiseCapture to tell users that they have to be in a "no noise" room to do the calibration. Right now, there is no such indications.

What do you think ? If you agree I can manage to do the modifications in the website.
@ebocher @nicolas-f

**Comment by Picaut** [comment]
Yes. It is planned with the release of the official version of NoiseCapture, soon.

**Comment by gpetit** [comment]
Ok, so let me know when it will be ok.
In my opinion, we can already prepare the documentation, because actual users already needs clarifications

**Comment by Picaut** [comment]
Information are already given at:
https://github.com/Ifsttar/NoiseCapture/wiki/4.-NoiseCapture-App

Text/figures could be re-used in the website.

**Comment by Picaut** [comment]
Calibration is also described inside the application, in the Help page.

**Comment by nicolas-f** [comment]
> In the meantime, we probably also should add a sentence in the "calibration" part of NoiseCapture to tell users that they have to be in a "no noise" room to do the calibration. Right now, there is no such indications.

What is the message/image to display in the android calibration activity ?

**Comment by Picaut** [comment]
One can mention
"The calibration procedure requires the use of a calibrated reference device such as a sonometer or calibrated smartphone. For more information, refer to the **help page** of the application".
Add the corresponding link to  **help page** (NoiseCapture/app/src/main/assets/html/help.html)
Add a button "OK" to discard the message

**Comment by Picaut** [comment]
It could be useful to add also videos on the website to show how to calibrate a smartphone using a calibrator (with external microphone) or a reference device.
