### ISSUE TITLE
Statistics on leaflet map page

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#140]
Leq(1s) count and area (m²) covered for each country.

```sql
select name_0, sum(st_area(st_transform(np.the_geom,3857))) covered_area, sum(measure_count) sumlen from noisecapture_area np, gadm28 ga where np.the_geom && ga.the_geom and st_intersects(st_centroid(np.the_geom), ga.the_geom) and not ST_ISEMPTY(np.the_geom) group by name_0 order by sumlen desc;
``` 

| country |            covered_area(m²) |           sumlen(seconds) |
|------------------|---------------------------------|------------------------|
| France           | 8473300,80381338                | 171843                 |
| Switzerland      | 2582033,09074851                | 97284                  |
| Colombia         | 218628,113180074                | 20341                  |
| Italy            | 410950,704729372                | 15928                  |
| Israel           | 157248,562695116                | 12932                  |
| Netherlands      | 436087,092076944                | 6395                   |
| Portugal         | 130358,473905159                | 4641                   |
| United Kingdom   | 7599,3729181281                 | 1897                   |
| Sweden           | 6430,23862285                   | 1660                   |
| Norway           | 4091,9700326254                 | 1327                   |
| Spain            | 52611,0432795066                | 1299                   |
| Chile            | 36243,1631473285                | 1119                   |
| Luxembourg       | 28059,223082666                 | 457                    |
| Bulgaria         | 1753,7014426552                 | 320                    |
| Brazil           | 10522,2086556954                | 313                    |
| Mexico           | 1753,7014426254                 | 298                    |
| Peru             | 3507,4028853137                 | 254                    |
| Germany          | 16367,8801311533                | 133                    |
| Greece           | 8768,5072132955                 | 132                    |
| Northern Cyprus  | 3507,4028853467                 | 106                    |
| Canada           | 1753,7014426166                 | 83                     |
| Belgium          | 39750,5660334432                | 71                     |
| Tunisia          | 4091,9700328702                 | 69                     |
| United States    | 1169,1342950678                 | 27                     |
| Indonesia        | 1169,1342951637                 | 8                      |
| Algeria          | 1753,7014427425                 | 7                      |
| Morocco          | 584,5671474817                  | 1                      |

**Comment by ebocher** [comment]
Add a rank is enough   :  France : 1; Switzerland :  2; ...

**Comment by pierromond** [comment]
Some nice statistics: http://cs.everyaware.eu/event/widenoise/statistics

**Comment by nicolas-f** [comment]
@Picaut @pierromond @gpetit 

Do you want to display statistics using array or graphics ?

If graphics I can use ChartJS http://www.chartjs.org/samples/latest/charts/bar/stacked.html

**Comment by Picaut** [comment]
Why not. Use graphics, only if necessary,

**Comment by nicolas-f** [comment]
Tag cloud

![image](https://user-images.githubusercontent.com/1382241/29613499-90ba446c-8806-11e7-8d08-c01eb7c53385.png)

**Comment by nicolas-f** [comment]
For the distribution I have crafted a sql query in order to enlarge statistical bins with greater measure length:

```sql
select time_length::int / power(10, length(time_length::varchar) - 1)::int *
 power(10, length(time_length::varchar) - 1)::int as fromValue,
(time_length::int / power(10, length(time_length::varchar) - 1)::int + 1) * 
power(10, length(time_length::varchar) - 1)::int toValue, count(*) total_tracks
 FROM noisecapture_track t group by fromValue, toValue order by fromValue;
```

| From  | To    | Count |
|-------|-------|-------|
| 1     | 2     | 42    |
| 2     | 3     | 84    |
| 3     | 4     | 81    |
| 4     | 5     | 74    |
| 5     | 6     | 64    |
| 6     | 7     | 64    |
| 7     | 8     | 59    |
| 8     | 9     | 69    |
| 9     | 10    | 71    |
| 10    | 20    | 708   |
| 20    | 30    | 322   |
| 30    | 40    | 506   |
| 40    | 50    | 155   |
| 50    | 60    | 95    |
| 60    | 70    | 254   |
| 70    | 80    | 81    |
| 80    | 90    | 59    |
| 90    | 100   | 56    |
| 100   | 200   | 448   |
| 200   | 300   | 204   |
| 300   | 400   | 164   |
| 400   | 500   | 94    |
| 500   | 600   | 97    |
| 600   | 700   | 55    |
| 700   | 800   | 46    |
| 800   | 900   | 28    |
| 900   | 1000  | 33    |
| 1000  | 2000  | 120   |
| 2000  | 3000  | 31    |
| 3000  | 4000  | 14    |
| 4000  | 5000  | 3     |
| 6000  | 7000  | 2     |
| 10000 | 20000 | 1     |

**Comment by nicolas-f** [comment]
Number of tracks over the last 8 weeks

![image](https://user-images.githubusercontent.com/1382241/29712965-af1b43f6-899c-11e7-8dd6-db7248e65308.png)

**Comment by nicolas-f** [comment]
Integration and duration label display

![image](https://user-images.githubusercontent.com/1382241/29774030-48ca6b84-8c00-11e7-9fd3-b0208fbe8d17.png)

**Comment by nicolas-f** [comment]
Finished awaiting pull request

http://nicolas-f.github.io/NoiseCapture

**Comment by nicolas-f** [comment]
Must be moved to NoisePlanet
