### ISSUE TITLE
User input after the end of measurements

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#15]
Give the user the ability to add the following information to each measurement:
- Description (not uploaded)
- Predefined tags (uploaded)
- Photo (not uploaded)
- Pleasantness slide (Unpleasant->Pleasant) (uploaded)

Not uploaded information stay in local database.

**Comment by nicolas-f** [comment]
@Picaut Only tags are uploaded ?

**Comment by Picaut** [comment]
Tag + Pleasantness should be uploaded

**Comment by nicolas-f** [comment]
First gui iteration

![userinput](https://cloud.githubusercontent.com/assets/1382241/15467223/a9e4d5f6-20dd-11e6-8a36-07d20094848e.png)

**Comment by nicolas-f** [comment]
What is the initial list of tag ?

**Comment by nicolas-f** [comment]
Last gui state with tags from Arnaud C. and Pierre A.

![noisecapture_comment](https://cloud.githubusercontent.com/assets/1382241/15608428/24875696-241a-11e6-9c21-3043de06c799.png)

**Comment by nicolas-f** [comment]
Aligned

![commentalign](https://cloud.githubusercontent.com/assets/1382241/15609136/8a1a1120-241e-11e6-87c4-488aa75de79f.png)

**Comment by nicolas-f** [comment]
Photo picking and storage is working. Touch photo for full screen using built-in photo viewer

![commentphoto](https://cloud.githubusercontent.com/assets/1382241/15710005/2ec641c0-2808-11e6-8cde-95924928c5f2.jpg)

**Comment by nicolas-f** [comment]
done
