### ISSUE TITLE
Remove post-processing (reference profile) from production

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#151]
Remove post-processing (reference profile) from production and only compute the LA50 of all laeq1s of measurements in hexagons.

**Comment by Picaut** [comment]
We can consider that the ZIP files (which can be used by third parties) **must contain all raw data without filtering or pre-process**. Considering this, the hexagons should only reprent data that are really inside the hexagons. This is validate with @ebocher.

**Comment by ebocher** [comment]
Thanks. Pie chart profiles must be also remove on the website. Nop ?

**Comment by nicolas-f** [comment]
Now the time donuts show the measurements hours.

**Comment by ebocher** [comment]
OK so to have a complete profile we must have a set of measures for a week

**Comment by nicolas-f** [comment]
Done
