### ISSUE TITLE
Measure lost if app on background.

### ISSUE THREAD

**Issue by SPalominos** [Ifsttar/NoiseCapture#159]
When you launch a measure, if the app stays in the background for more than 5 minutes while and other heavy one is running (like Pokemon Go), when you go back to NoiseCapture, the measure disappears.
The measure screen is waiting for the launch of a new one and in the history a measure is present but with a length of 0 seconds. 

Info :
- NoiseCapture version : 0.4.8 (Beta) 14 jun 2017 r.37a2279
- Phone : HUAWEI P9 lite (HUAWEI VNS-L31)
- Android version : 7.0

**Comment by nicolas-f** [comment]
Should be fixed with the last version (from 0.5.0)
