### ISSUE TITLE
Add categories to Tags

### ISSUE THREAD

**Issue by pierromond** [Ifsttar/NoiseCapture#162]
The tags should be grouped in 2 categories. 

The first tags are about the kind of sources which are important to understand the result of the measure (wind, rain, etc.). It finally concerns the measurement conditions (or proximity sound sources).  I propose the following subtitle "Measurement Conditions".

The second group is about the three categories of sound environment classically used in soundscape studies ("Human, Mechanical and Nature"). I propose the following subtitle "Type of Sound Environment".

If we add the three following tags: , "works", "air_traffic", "entertainment" they should be in the first category. By the way, I don't think we should add so much sound sources, because the list can be hudge ! "music, etc." see https://serv.cusp.nyu.edu/projects/urbansounddataset/taxonomy.html

**Comment by nicolas-f** [comment]
If there is a relation between tags maybe it is necessary to force this relation by using an adapted graphical user interface like this ?

![image](https://user-images.githubusercontent.com/1382241/27427535-a2ae1574-573f-11e7-9de9-964a3cc8f19b.png)

**Comment by pierromond** [comment]
I think it could be too much complicated for the user. Discrete subtitles and few tags (max. 9 or 12) should be preferred in my opinion.
If the users report "too much frustration" about the tags, maybe it is a good solution to let a free comment field.

**Comment by Picaut** [comment]
I am agree with @pierromond. It must be simple.

**Comment by gpetit** [comment]
+1.
And just as a feedback, for the last measures I made (e.g in Firenze (city center or CNR)) I was not able to find tags that really suits to my situation (for example, crowd, with vehicules, ...). So I think we should remove/add some tags

**Comment by Picaut** [comment]
Crowd = "Human"
Vehicles =  #"Traffic"

What tags do you want to add for example ?

Note: since the last version there are 3 news tags #109

**Comment by pierromond** [comment]
With three tags for the sound environments **#Human #Mechinal #Natural, All the sound sources of the earth should fit** :) (maybe only the music sound sources are difficult to put in one of this categories, see https://serv.cusp.nyu.edu/projects/urbansounddataset/taxonomy.html)
Also:
- Crowd -> Human
- Vehicules -> Mechanical
- Airplane -> Mechanical
- Works -> Mechanical
- School -> Human
- etc.

Only this three tags are useful for a simple soundscape analysis. If we want a more detailed soundscape analysis, there are no other choices that to put 20 or 30 possibilities of sound sources, or a free field.

I think all the **supplementary tags have only to be think to help us to filter the data**. Also it is why I think **"measurements conditions" subtitle** is important. Test, Rain, Wind, etc. are not asked for soundscape analysis, but only to help us to know why these measurements are different from other ones.

**Comment by Picaut** [comment]
Thank. I understand, but some people ask us explicitely to add these tags. I think that Vehicles, Airplane and Works are useful... but we can discussed about it later.

**Comment by Picaut** [comment]
No change. Just the label "Predominant sources" to rename by"Tags"

**Comment by pierromond** [comment]
A new proposition, based on http://d3hu9binmobce5.cloudfront.net/content/royopensci/3/3/150690/F3.large.jpg and http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.722.606&rep=rep1&type=pdf

Should we use different colors ?

![image](https://user-images.githubusercontent.com/1659842/28769379-88b0f3ca-75db-11e7-9f45-7b9efc2028a7.png)

![image](https://user-images.githubusercontent.com/1659842/28769389-90db33bc-75db-11e7-97b9-fa3c3390eb92.png)

**Comment by nicolas-f** [comment]
Chatting become Voice
entertainment removed
footsteps removed
natural removed
mechanical removed
human removed
entertainment removed

**Comment by nicolas-f** [comment]
Last version of tag activity

![image](https://user-images.githubusercontent.com/1382241/28865518-7b87cf20-7770-11e7-9fc3-9f388fe28231.png)

**Comment by Picaut** [comment]
Great. Good job
