### ISSUE TITLE
Create multiscale hexagonal maps

### ISSUE THREAD

**Issue by ebocher** [Ifsttar/NoiseCapture#164]
In order to improve the rendering of the collected measures, we proposed to create a multi-scale hexagonal maps based on a fractal generation procedure. see http://www.mylovedone.com/SpatialSynthesisVol2Book2/escher/FractalEarth.html

From the small hexagons (currently 15 meters) , the idea is to create several levels (as for tilling and pyramids) :  15 , 405, 3645 and 10935...
The hexagon maps will show the number of measures.

**Comment by ebocher** [comment]
https://docs.google.com/spreadsheets/d/1t9OJb-Z9vnHYKw6fWR82Wml4Dj9ePnNoOzqDw3v_PwU/edit#gid=0

**Comment by ebocher** [comment]
http://www-personal.umich.edu/%7Ecopyrght/image/solstice/sum04/sampler/index.html

**Comment by pierromond** [comment]
Good Idea, I think it will be more nice and if the hexagon maps show the number of measures it will be great. 

Just to say : I don't know if you think to choose color for the hexagons. 
- I think it should not be correlated to the median sound level for biggest tiles. Some others maps that it is possible to find on the web do that, but I think it doesn't have any sense for acoustics noise levels. 
- Maybe a colorscale linked to the measurements number ?

**Comment by ebocher** [comment]
The big hexagons maps will show the number of measures. The style will be based on a color ramp as it's done for heapmap.

**Comment by pierromond** [comment]
Super !

**Comment by nicolas-f** [comment]
The processing is done. I have to found how to render the measurement clustering now.

![hexa](https://user-images.githubusercontent.com/1382241/28923796-88fe3672-785f-11e7-96df-58bf0d0f5aeb.png)

**Comment by nicolas-f** [comment]
Current state.

Leaflet is using WFS with this CQL in order to fetch the minimal data
 `CQL_FILTER: 'BBOX(the_geom, '+bbox.toBBoxString()+') AND "cell_level"=' + zoom_lvl_to_cell_lvl[map.getZoom()]`

So the rendering is done on client side

![test](https://user-images.githubusercontent.com/1382241/28967954-fbfbdbc0-791d-11e7-9417-fc6bb0d55221.gif)

**Comment by Picaut** [comment]
Just great

**Comment by ebocher** [comment]
Super +10000
