### ISSUE TITLE
Less values in pleasantness

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#166]
The user can currently set a pleasantness with 100 values. ( a slide bar with 100 steps)

Reduce this option to 5 steps in order to give the ability to the user to set the same pleasantness between two measures.

Any feedback ? @pierromond @Picaut @gpetit @ebocher

**Comment by pierromond** [comment]
Why not. 5 or 7 steps are generally used even if I don't really see why it could be more or less useful.

**Comment by ebocher** [comment]
Why not a single scale with 4 values : Pleasant, Rather pleasant, Rather unpleasant, Unpleasant
See https://books.google.fr/books?id=1AMmDwAAQBAJ&pg=PA33&lpg=PA33&dq=sound+pleasantness++scale&source=bl&ots=XU0BdThEIQ&sig=bPUscXiLJiplyp41TChzl2Iq5kY&hl=fr&sa=X&ved=0ahUKEwjVwc3t_JTVAhVGXhQKHW1jDvEQ6AEITzAG#v=onepage&q=sound pleasantness scale&f=false

**Comment by pierromond** [comment]
All theses scales are possible... Likert scales (as you propose) are more difficult to convert into numeric values and are more often used with 5 or 7 points (with neither pleasant, neither unpleasant at the middle). The standards that I know more often recommend to put only two information at the opposite part of the scale (Pleasant to Unpleasant) and after to let a numeric scale between that (semantic differential scales).

If we use the semantic differential scale (which is my preference), 4,5,7 or 1000 values doesn't change anything. It changes only the resolution of the scale (and so, the user experience).

Some info here for example: https://www.newnorth.com/likert-vs-semantic-differential-questions-in-customer-satisfaction-surveys/

**Comment by Picaut** [comment]
OK. 5 seems a quite good choice.

**Comment by pierromond** [comment]
I am also ok for 5, with "Unpleasant" and "Pleasant" at each side of the bar.

**Comment by nicolas-f** [comment]
Any suggestion on the rendering ?

![image](https://user-images.githubusercontent.com/1382241/28872003-74df3ee4-7787-11e7-9612-0a231347f01a.png)
