### ISSUE TITLE
Displayed LAeq window size

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#168]
Currently (beta) the window size of the displayed leq is 125ms. 

So the level is refreshed 8 times per second. 

As we are using the Hann window with a 66 % overlap the FFT on 125ms are done 24 times per second.

In debug mode my Motorolla phone is not able to process this in realtime (it have to process the 1s fft also)

Could we go to a 250 ms window size ? Or maybe automatically go to a rectangular window if the Android phone is not able to process the audio signal in real time ? Do you have another solutions ?

@Picaut

**Comment by Picaut** [comment]
Both solution are possible. The idea is that this settings be automatic (250ms or rectangular windows).

**Comment by nicolas-f** [comment]
NoiseCapture now switch to rectangular. But it may be not sufficient on some low cost smartphones.
