### ISSUE TITLE
Add an information for the Calibration procedure

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseCapture#170]
When the user goes to the Calibration menu option, display an information that mentions that the user must use a reference device to perform the calibration.

**Comment by nicolas-f** [comment]
Link to #132

**Comment by nicolas-f** [comment]
There is also currently a warning when the user arrive at the measurement activity

> Remember that this application will never replace a certified and calibrated sound level meter.

Should we also add a link in this message about the calibration step ?
