### ISSUE TITLE
Display a notification to invite users to see community map

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#192]
Display a notification on android to invite users to see community map.

Proposed text

title: Community measurements
content: Visit http://noise-planet.org, browse the map of all the measurements made by the community 

The question is when and at which occurrence to display this notification ?

**Comment by Picaut** [comment]
Use the link to the map, instead of the Home Page of Noise-Planet.
The occurrence may be based on the number of consultations of the 'Map' page of the App (every 10 ?). You can also add a parameter in the SETTINGS to not display this notification.
