### ISSUE TITLE
Reduce length of sound level values in the 'track.geojson' file in the ZIP file

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseCapture#193]
One can reduce the size of the file by considering only 2 values after the comma for the sound level.
Example: '68.60630458101848' ->'68.61'

**Comment by nicolas-f** [comment]
Native Android Json drive does not handle formatting of numeric type.

In order to do this, we have to switch to another JSon library or write it ourself.

**Comment by nicolas-f** [comment]
I used float instead of double, so the library has reduced the output to "74.68488"
