### ISSUE TITLE
Information on the "user profile"

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseCapture#195]
One can be interested to know if a given user has notions in the field of noise (for the data quality). The question could be asked at the first use of the application (YES, NO, NO ANSWER) and available in the settings.

**Comment by nicolas-f** [comment]
May be an optional checkbox in the privacy screen because we have already a lot of dialogs on the first start ?

**Comment by Picaut** [comment]
Yes. Good idea.
EN: "I have some knowledge in the field of noise"
FR: "J'ai quelques connaissances dans le domaine du bruit"
You will need to add this in the metadata, such as user_profile (0: NO; 1:YES)

**Comment by pierromond** [comment]
Good idea !

Maybe we could add levels:

How do you evaluate your knowledge about sound environments:
0. No answer
1. Novice
2. Competent
3. Expert / Profesional

**Comment by nicolas-f** [comment]
What is the planned version for this ?

**Comment by nicolas-f** [comment]
New option on small screen

![image](https://user-images.githubusercontent.com/1382241/29557461-71a586b4-8729-11e7-808d-81a1efe5a565.png) ![image](https://user-images.githubusercontent.com/1382241/29557485-8af70764-8729-11e7-8b2d-2e6d01516dbf.png)

**Comment by nicolas-f** [comment]
@ebocher moved

![image](https://user-images.githubusercontent.com/1382241/29558140-8a97b3c0-872b-11e7-8062-463c35def99a.png)


Settings

![image](https://user-images.githubusercontent.com/1382241/29557982-0c5ef4c8-872b-11e7-9832-c9cde82d9433.png) ![image](https://user-images.githubusercontent.com/1382241/29558005-2169d2f2-872b-11e7-938a-88b6eb691263.png)

**Comment by ebocher** [comment]
+ 100

**Comment by nicolas-f** [comment]
Some users may not see the question, so this is now a modal question when the user click on continue:

![image](https://user-images.githubusercontent.com/1382241/29566293-9e49499c-8749-11e7-98c0-3c45728e6439.png)
