### ISSUE TITLE
Add satellite map on the leaflet map (Android)

### ISSUE THREAD

**Issue by ebocher** [Ifsttar/NoiseCapture#200]
var esriworldimagery = L.tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
	    attribution: 'Tiles &copy; Esri &mdash; Source: Esri, i-cubed, USDA, USGS, AEX, GeoEye, Getmapping, Aerogrid, IGN, IGP, UPR-EGP, and the GIS User Community'
        });

var baseLayers = {
            "OpenStreetMap": osm,
             "Images satellites": esriworldimagery
        };

**Comment by nicolas-f** [comment]
Already done 14 days ago:

https://github.com/Ifsttar/NoiseCapture/commit/f7d17144ea3f74045fb89c32c66a80b5895cd7cb#diff-d0e2779c406aa041338af03257428b9bR109

**Comment by ebocher** [comment]
Oupps... I will update my version sorry.
