### ISSUE TITLE
Reduce the scale demoninator to display the location of measures

### ISSUE THREAD

**Issue by ebocher** [Ifsttar/NoiseCapture#207]
The scale denominator must be adapted when  the location of measures is rendered.
It's not necessary to display both cluster of hexagons and point locations.
Try this link http://onomap.noise-planet.org/#14/45.7568/4.8234

The same about noise hexagons

**Comment by nicolas-f** [comment]
Duplicate to https://github.com/Ifsttar/NoiseCapture/issues/202
