### ISSUE TITLE
Possible re-upload of measure

### ISSUE THREAD

**Issue by SPalominos** [Ifsttar/NoiseCapture#209]
On the 'History' menu, on selecting the blue cloud with a check, the popup menu contains the action 'Upload to the comunity' (Transférer vers la communauté). After pressing it, a text box appears with the message 'upload of the measure' (Transfert de la mesure).
And those action can be done again and again ... Maybe it could cause a multi upload of the same measure ?

Phone : Huawei P9 lite
Android : 7.0
NoiseCapture : 1.0.0 23 août 2017

**Comment by nicolas-f** [comment]
Currently, if the measurement is uploaded twice, only one is stored in the database.

Duplicate with https://github.com/Ifsttar/NoiseCapture/issues/57

**Comment by Picaut** [comment]
Does-it means that the measurement is updated with the last modification ?

**Comment by nicolas-f** [comment]
No, nc_process script will skip the processing of the zip file and place it in onomap_error folder (instead of onomap_archive)

**Comment by ebocher** [comment]
Is the onomap_error folder cleaned ?

**Comment by nicolas-f** [comment]
I try to not delete zip files, even if there is an issue with a zip file.

**Comment by nicolas-f** [comment]
Its the most precious 💍  file over there

**Comment by Picaut** [comment]
When the measurement has already been uploaded, the Upload action must be disabled
