### ISSUE TITLE
Share/Export measure feature

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#21]
Add a method to share/export measure without requesting authorization to read/write files in android.

**Comment by nicolas-f** [comment]
Done.

Currently all content are exported using zip file.

https://github.com/Ifsttar/NoiseCapture/commit/8cfe00e77e107f640b530513aaff871b5c4fdbf3

![export](https://cloud.githubusercontent.com/assets/1382241/15397348/2e6908e8-1de0-11e6-8bcc-2ee05138b4d6.png)

**Comment by Picaut** [comment]
Seems perfect

**Comment by nicolas-f** [comment]
TODO export zip on history
Share message on result page:
"Here we measure x dB(A) at lat,long (url)"

**Comment by nicolas-f** [comment]
Url is map with lat long and if available record id
http://webcarto.orbisgis.org/noisemap.html#12/37.7630/-122.4437

**Comment by ebocher** [comment]
Don't forget to store also some metadata about the column names.

**Comment by nicolas-f** [comment]
@ebocher where ?

**Comment by ebocher** [comment]
Maybe in another file when you click on  create zip file.

**Comment by nicolas-f** [comment]
done 62402fc64733b8ec7b75cb10c6ba2c76b985fcfd
