### ISSUE TITLE
Alternative store

### ISSUE THREAD

**Issue by hferee** [Ifsttar/NoiseCapture#218]
Could you consider hosting the app on an alternative app repository like f-droid? https://f-droid.org/

Or alternatively using your own compatible repository: https://f-droid.org/docs/Setup_an_F-Droid_App_Repo/

**Comment by gpetit** [comment]
Hi @hferee, thanks for your interest in NoiseCapture and for your question.

It may be a good idea. We will consider your request with the team asap.

**Comment by mfaure** [comment]
Hey, I just discovered NoiseCapture from the [Numerama news](http://www.numerama.com/sciences/287446-le-cnrs-a-besoin-de-vous-pour-cartographier-lenvironnement-sonore.html#commentaires). This app looks really cool!

I don't have access to Google Play but only to F-Droid. I would be really happy to contribute (as I already do for OpenStreetMap with StreetComplete).

I think you would leverage the spread of NoiseCapture by putting it on F-Droid.

Here is the [Submitting to F-Droid Quick Start Guide](https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/)

**Comment by gpetit** [comment]
Thanks @mfaure for your message. 
As explained before, we are seriously considering the question. We just have : 

- to check if it can introduce any unexpected problem and then

- if it's ok, to organize our development process in order to provide the app on an alternative store (i.e F-Droid)

**Comment by mdoube** [comment]
It would also be nice to keep publishing builds here on Github, somehow that stopped after Beta 0.5.0.

https://github/ifsttar/NoiseCapture/releases

**Comment by nicolas-f** [comment]
About releasing the apk. I stopped this because some people use NoiseCapture apk under android emulator and publish some measurements. This is why we have Antartica in the list of countries.. (that cause also a crash on dump for data.noise-planet.org)

**Comment by mdoube** [comment]
If not here, then can I suggest Aptoid store, and Yandex? Although, I expect that someone with an emulator can install apps to get APKs from these stores as well as Google Play.

**Comment by nicolas-f** [comment]
Yandex is interesting. Could be used to publish to China https://blog.aptoide.com/1-million-devices-china/

**Comment by nicolas-f** [comment]
Todo: Register in Aptoid using Ifsttar or CNRS account.

**Comment by gpetit** [comment]
Dear all, 

NoiseCapture is now available on Aptoide : https://noisecapture.en.aptoide.com/

Please contact us if you encouter any problem

**Comment by nicolas-f** [comment]
Published on alternative store

**Comment by Poussinou** [comment]
@IzzySoft

**Comment by IzzySoft** [comment]
@Poussinou https://gitlab.com/IzzyOnDroid/repo/issues :wink: And because it's you, just today without that task: https://apt.izzysoft.de/fdroid/index/apk/org.noise_planet.noisecapture

**Comment by Poussinou** [comment]
Oh yes sorry. I'll try to remember next time (I just found this app and notify you on the fly...)

Thanks 👍
