### ISSUE TITLE
NoiseCapture Party events

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseCapture#220]
One propose to formalize the NoiseCapture Party, in order to help NoiseCapture Ambassador for animating the event.

Inside the application:
- [ ] Add en entry "NoiseCapture Party" in the settings
- [ ] Add a sub-entry of type "checkbox" for "Participate to a NoiseCapture Party" with the additional text "Contributors should obtain a valid code from the people in charge of the event"
- [ ] Add a sub-entry of type "text" with the label "NoiseCapture Party code" for the corresponding code. This entry is activated if the checkbox is selected.

Inside the ZIP file:
- [ ] Add a new property for the data : "NoiseCapture_Party_code" (or similar)

Within Noise-Planet.org, we could duplicate and simplify the current map, for a given NoiseCapture Party (at a specific link, by filtering the data with the code), with basic statistics (Number of contributors, Number of measurements, Total duration), history, a short description (who, when, information...)

**Comment by nicolas-f** [comment]
If a NoiseParty is identified by a time range and a location area I don't think it is necessary to add new properties inside NoiseCapture.

I could enhance the server side processing to be able to create NoiseParty by providing the following information:

- NoiseParty title
- NoiseParty hashtag
- Start date
- End date
- Area polygon
- url of event web page
- description text

Also we could dump each NoiseParty as a single zip file in data.noise-planet.org

I say that because I don't think it will be always straightforward for users to go inside the NoiseCapture preferences and type the good code at the right place before doing any measurements..

**Comment by nicolas-f** [comment]
Todo:

Reduce description field height and place a new free text field "NoiseParty tag". This text field default value gather the last stored measurements noiseparty tag (with different measurement identifier). Lock this text field if the measurements is already uploaded.

On server side. Add two tables

### noisecapture_party
```
id_party pk
title text
tag text
description text
```

Update table
### noisecapture_area
Add field (accept null values)
```
id_party int
```
### noisecapture_track
Add field (accept null values)
```
id_party int
```

When parsing the zip file coming from android phones, if the noiseparty_tag is not defined in `noisecapture_party` table then set null to `id_party`

**Comment by nicolas-f** [comment]
Comment activity:

The constraint of character tag is alphanumeric (upper case) and _

![image](https://user-images.githubusercontent.com/1382241/30420880-43004366-993b-11e7-891c-d0c86537c309.png)![image](https://user-images.githubusercontent.com/1382241/30420944-7cd8c568-993b-11e7-80e1-946eec1a31e0.png)

**Comment by gpetit** [comment]
Seems perfect.
It means that you are forcing the upper case ?
How do you proceed if the user want to enter special characters (e.g @ or é) ? You display a warning message after the lose of focus ?

**Comment by nicolas-f** [comment]
The user cannot type special characters. upper case is automatic (dont have to exit the textinput)

**Comment by gpetit** [comment]
perfect :+1:

**Comment by Picaut** [comment]
Perfect

**Comment by nicolas-f** [comment]
Web page:
List of all NoiseParty on the top right side

When selected:
- Load the new hexagon layer
- Load title and description and open the home panel
- Zoom to the noisecapture party extent 

Statistics, history, hexagon info are filtered using noise capture party identifier.

![image](https://user-images.githubusercontent.com/1382241/30590671-f1d78022-9d3f-11e7-9e6c-14c4a5899a8e.png)

**Comment by nicolas-f** [comment]
Todo:

Add 4 fields:

- start_time timestampz
- end_time timestampz
- filter_time boolean
- filter_area boolean

pk_party is not attributed if the party does not exist, if filter_time is true and time range does not contain the measurement time, if filter_area is true and the_geom does not contains the start point of the measurement.
