### ISSUE TITLE
Not able to modify the intensity of sound

### ISSUE THREAD

**Issue by Whisper40** [Ifsttar/NoiseCapture#226]
Hello, i'm currently trying to modify the intensity of soud after uploading the measure but i can't.

I can't put it on "Agréable", that's lock.
And the same for " Désagréable "

And it's the same for sources of sounds " speak,water.."

Android 7.0 - OP3

**Comment by nicolas-f** [comment]
Hi thanks for the feedback,

Measurements can only be sent once, so pleasantness and tags cannot be updated when the transfer is already done.

**Comment by Whisper40** [comment]
Oh.. ok. That should be an upgrade

**Comment by nicolas-f** [comment]
Maybe we can display a message when the user tap on disabled fields ?

**Comment by Picaut** [comment]
Yes. Good idea.
