### ISSUE TITLE
Processing of wps upload task

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#24]
Onomap service on receiving android Rest call save the POST data into as zip file.

This zip is stored in "processing" folder. A new thread is triggered in order to check and parse the content of the zip file.

The processing WPS fetch zip files stored in "processing" folder and check if the zip content correspond to expected files name.

The property file and geojson are parsed then used to feed the PostGIS database.

Once done, the zip file is moved to an archive folder.

**Comment by ebocher** [comment]
+1
