### ISSUE TITLE
NoiseCapture question

### ISSUE THREAD

**Issue by Rafael-Guzman** [Ifsttar/NoiseCapture#279]
Hello Team, 

I just discovered today Noise-Planet.org and learning about it, I'd like to get involved on this project more and share data for environmental noise assessment, I'm currently exploring the capabilities of static site generators to publish projects and integrate webmaps, I'm trying to figure out how I could integrate this project into a static site like jekyll running on a github page, by displaying the data I capture on my local area, it would be so cool if I could create a noise map for my local community and post it on my personal site

Regards,

**Comment by Picaut** [comment]
Dear Raphael,
It could be a good idea to share maps using specific Widgets from the Noise-Planet project. But, it is not available yet. May in the future.
Best regards

**Comment by nicolas-f** [comment]
Hi,

WMS tiles are only aggregated to all measurements and specific noise party code. You cannot filter rendered data on our servers for a specific user.

Have a look at the official leaflet code hosted here https://github.com/Ifsttar/NoisePlanet/tree/gh-pages/map_noisecapture
