### ISSUE TITLE
The maps is not displayed with Android 9 MIUI

### ISSUE THREAD

**Issue by baudav** [Ifsttar/NoiseCapture#296]
Maps is not displayed in the master screen, and maps not displayed in MAPS tab.
I use MiMix3 MIUI10.2.1.0 Android 9 PKQ1.180729.001

![image](https://user-images.githubusercontent.com/10183995/53686843-e452d580-3d2c-11e9-83f0-09a55613482a.png)
![image](https://user-images.githubusercontent.com/10183995/53686848-f6cd0f00-3d2c-11e9-975a-52d0963a0179.png)

**Comment by nicolas-f** [comment]
Fix released in Beta version (v  1.2.8).

Please let us know if it works on your device. Thanks

**Comment by baudav** [comment]
no, it's not work. Same result as before

**Comment by gpetit** [comment]
@baudav are you using the beta version mentionned by @nicolas-f ? I guess no ...
@nicolas-f can you tell us how people can ask to be part of the beta tester program (if it's still open) ?

**Comment by nicolas-f** [comment]
Hi,

Version 1.2.9 fix the null pointer issue. It has been tested on Android 9 emulator, map is displayed without issues.

Please check you have this version, or you can enroll for beta testing here:

https://play.google.com/apps/testing/org.noise_planet.noisecapture

**Comment by baudav** [comment]
ok, the new beta (1.2.9 22mars) work fine.
