### ISSUE TITLE
Release of 1.2.13

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#310]
What is missing for the release of version 1.2.13 (currently beta) ?

@Picaut @pierromond

**Comment by gpetit** [comment]
@nicolas-f have you integrated the Corsican and Portuguese languages?

**Comment by nicolas-f** [comment]
In order to support Corsican I would have to use something else than Android API for localisation.

I will push Portuguese (Brazil)

**Comment by pierromond** [comment]
@nicolas-f @gpetit Finaly, everything about alternative calibration is ok ? The text, etc. ? If yes, it is ok for me.

**Comment by nicolas-f** [comment]
There is some missing translation in languages (all except French and Portuguese). May be we should ping the translators ?

**Comment by gpetit** [comment]
Yes, we can send them an email thanks to the Transifex platform to ask them if they want to complete

**Comment by gpetit** [comment]
I will contact them if you want

**Comment by nicolas-f** [comment]
Thank you. That's nice. :)

**Comment by gpetit** [comment]
Done. Just have to wait.
For the spanish one, maybe @pierromond can translate the 19 missing chains ?

**Comment by pierromond** [comment]
Done ;)
