### ISSUE TITLE
Automated transfer of measures not working anymore

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#315]
When checked in parameters, automated transfer of measurements to community server is not automatically triggered anymore.

**Comment by gpetit** [comment]
Waow ... that's new ? Or linked to the last release ?

**Comment by nicolas-f** [comment]
I don't know how long we've had this problem.

**Comment by nicolas-f** [comment]
So the release is postponed until this issue is fixed

**Comment by gpetit** [comment]
But we are still receiving measures. So what is the différence between these contributions and the other one that are not sent (in terms of configuration) ?

**Comment by nicolas-f** [comment]
There is manual upload of measurements (when user click on upload or share with community in history tab) and automated upload (transfer of measurement when internet is available).

**Comment by gpetit** [comment]
Ok so it means that all the measures obtained have been sent manually by the users ... I'm even more impressed

**Comment by nicolas-f** [comment]
I don't know if release version of NoiseCapture have this issue
