### ISSUE TITLE
NoiseCapture App

### ISSUE THREAD

**Issue by EngYass** [Ifsttar/NoiseCapture#321]
Hi, 
I'm a Master student and my project on enviromental noise pollution monitoring. However, i used NoiseCapture App to capture the noise around. To ensure the quality of measurments, i have to calibrate my smartphone so, **Can you recommend me a microphone to calibrate my smarthpone ??**

**Comment by Picaut** [comment]
You could use an external microphone such as this one micw i436
https://www.amazon.fr/MicW-I436-Microphone-miniature-%C3%A9lectret/dp/B00510Y3KC 
with an acoustic calibrator (Class 1 or 2) 94dB @1kHz
Then, follow the procedure in NoiseCapture app.
This is what we do in our laboratory.
Best

**Comment by EngYass** [comment]
Thank you sir for the help.
Can i use this external Microhpone (MicW i436) with Android devices such as Samsung, Huawei ?
Also, What i need to do the Calibration is only **External Mic**, **Smartphone** and **NoiseCapture App** **right?**or missing something else
May you explaine a bit on this sentence  **(with an acoustic calibrator (Class 1 or 2) 94dB @1KHz)**
So appreciate if you guid me.

**Comment by Picaut** [comment]
You must connect the external mic of your smartphone, then go to the Calibration procedure on NoiseCapture App and choose the calibration method using a calibrator., and follow steps. A calibrator is an external device that produce a reference sound at a given sound level (should be 94dB) for a given frequency (1000Hz) -so you have to buy/find also this device. This is the same procedure that for calibrating a professional sound level meter (see for example: https://www.youtube.com/watch?v=LVPqIKdOirE -note that we have no link with this company; it is just an example). See also : https://noise-planet.org/noisecapture_calibration.html

If you don't want to buy an external microphone and use a calibrator, there is a new procedure in NoiseCapture (last release) that allows to calibrate the smartphone using the measurement of road traffic (with statistical consideration). You can use it following the steps inside the application. We don't have yet written a full tutorial for this.

**Comment by EngYass** [comment]
Ok Sir, I will try it ..
Thank you so much for your time.
May i know what is the purpose of connecting external Mic on the smatphone? 
I mean, we can use the Mic built inside smartphone.

**Comment by Picaut** [comment]
An external microphone is of better quality that the the built in microphone. In addition, you can easily use an acoustic calibrator for calibration (if the size/diameter of the microphone is compatible with the calibrator).

**Comment by drupol** [comment]
Hello,

Sorry for "necroposting" here, but I am also wondering which external microphone to use when the only option is a phone with USB-C.

The purpose here is to create a DIY Outdoor Noise Station with an old phone, to record noise surroundings.
