### ISSUE TITLE
Exchange rate for NoiseCapture app 3dB or 5dB

### ISSUE THREAD

**Issue by Oldfield007** [Ifsttar/NoiseCapture#332]
Hi, sound level meters can have a 3 or 5 dB exchange rate.  What is the exchange rate for the app?

Suggestion - this would be very helpful to include in the app specifications from the google play page.

**Comment by Picaut** [comment]
Thank you for your question.
If you mean "calibration gain", this value depend on the smartphone. The only way to find this value is to use one of the calibration method within the App.
Best regards

**Comment by Oldfield007** [comment]
Hi, the question is in regard to the software.  Can you change the dB exchange rate - and what is it set at 3 or 5dB.

The UK, Europe and many other places around the world have an exposure limit of 85dB(A),  a “3dB exchange rate” formula is applied, which means that for every **3dB** above 85dB(A), the maximum permitted exposure time is cut in half. **(Note: in the USA a 5dB exchange rate is used, because although 3dB change represents a doubling or halving of noise, this change is not readily perceived by the ear, at 5dB the ear will be able to notice the change in noise).** 

https://pulsarinstruments.com/en/post/understanding-3db-rule

**Comment by nicolas-f** [comment]
Hi,

The NoiseCapture software does not contain any regulatory indication of the maximum time of exposure to noise in a workplace. This software is for the measurement of noise in the outdoor environment.

**Comment by Oldfield007** [comment]
I understand - I just need to know is the software programmed for a 3dB or 5 dB exchange rate and can that value be changed anywhere.  The exchange rate is also pertinent to environmental noise as it determines if the noise doubles by 3 or 5 dB when measuring.

**Comment by Picaut** [comment]
There is +3dB when there is a doubling of energy (or +6dB in doubling the acoustic pressure).
Best regards.
