### ISSUE TITLE
high resolution noise capture map possibility

### ISSUE THREAD

**Issue by gfanini** [Ifsttar/NoiseCapture#343]
Could it be possible with noisecapture android app, (or any other app,) to make a noise map with say 1 m resolution (or whatever GPS allows) in order to find (intermittent) sources of noise ?

**Comment by gpetit** [comment]
Hi,
The GPS accuracy directly relie on the smartphone capabilities (note that to be optimal, the measures have to be done outdoor).
Once uploaded to our server, the measures having a GPS accuracy higher than 15m are excluded (to avoid measuring errors). Then, hexagonal cells agregates "good" measures within 15m radius.
Therefore, the NoiseCapture map does not seem to meet your needs.
I would rather advise you to work directly with the raw data, with a GPS accuracy that meets your needs.
