### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by jugendhacker** [Ifsttar/NoiseCapture#359]
We just received a inclusion request over at [F-Droid](https://gitlab.com/fdroid/rfp/-/issues/1917).

Currently I only see one problem here, please add [fastlane structure](https://gitlab.com/-/snippets/1895688) and tag a new release containing the metadata, so that on our side we don't have so much work maintaining the metadata.

**Comment by nicolas-f** [comment]
Hi,

It is not from us but it's a welcomed event.

It should not be difficult to add the fastlane folder, juste copy-paste actions..

We currently experience issues with a data over audio library so maybe we will wait to fix it before releasing a new version.

**Comment by jugendhacker** [comment]
Yeah no problem, just ping me here if you released the new version.

**Comment by nicolas-f** [comment]
It was published in Beta
It will be release in 1 week if there is no new bugs detected

**Comment by nicolas-f** [comment]
58 has been released and merged in master thank you

**Comment by jugendhacker** [comment]
Thanks for merging, but seems like you did not properly tag the latest version. Could you please tag it?

**Comment by nicolas-f** [comment]
Oh yes sorry, I had used the old master branch to create the tag. It's done now I recreated the tag v1.2.22

**Comment by jugendhacker** [comment]
Okay I finally managed to get our bot [looking over it](https://gitlab.com/fdroid/rfp/-/issues/1917#note_764011238).

Now some new problems appeared. First of all look at the fdroid scanner section and there the errors part. Here we can see that you use mutiple Maven repos that F-Droid does not allow, because it could not be guaranteed that they contain FOSS software. Second you could also see that your repo contains multiple prebuild jars which are usually also not accepted inside F-Droid. I'm not sure but they look like they could maybe be remove before the build on the F-Droid side or will this break something if they are missing during the build?

Also please take a look at the Gradle Wrapper section of the report and follow the hints it gives you.

**Comment by nicolas-f** [comment]
Sorry for the delay

 onomap-geoserver is another project for the server side of the application so it is not embedded into the android application.

Maybe you could scan only the **app** of this repository ?

thanks

**Comment by jugendhacker** [comment]
Yeah sure if `onomap-geoserver` folder is not needed for the build of the app we could just nuke it before building.

**Comment by jugendhacker** [comment]
I'm currently trying to build the app and saw 947a0ef8d57f9c6c5d2e3a3c958783d021f9686f is not included in the v1.2.22 release. We have two possible options now: you could tag another version including this change or if you say it's okay F-Droid could theoretically also build version 1.2.22 from based on 947a0ef8d57f9c6c5d2e3a3c958783d021f9686f, although I would prefer the first option.

**Comment by nicolas-f** [comment]
If I understand correctly F-Droid is requesting to have the master branch with the last commit always tagged ?

**Comment by jugendhacker** [comment]
No, we usually build based on the tags. But the commit I linked removes the repo that is not allowed by F-Droid but the v1.2.22 does not include this commit and if I try to build v1.2.22 our buildserver complains about the repo that is not allowed.

**Comment by nicolas-f** [comment]
I will try to tag without doing an actual release

**Comment by nicolas-f** [comment]
I release this version:
https://github.com/Ifsttar/NoiseCapture/tree/v1.2.22-rc3
With all updates (no change on Android program code)

**Comment by jugendhacker** [comment]
@nicolas-f sorry to bother you again, but could you maybe comment on https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10732#note_878422774 ?
