### ISSUE TITLE
Calibration activity

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#38]
Implement the calibration activity

Method A:

 - User click on start calibration button
 - A visual timer count down from X seconds to 0 seconds
 - Measurement of Leq starts
 - A visual timer count down from X seconds to 0 seconds
 - User set the expected (externally measured) value using a SeekBar from 72 dB to 102 dB.
 - Android store the gain factor to apply

User is forced to choose theses values as Android device may not able to measure linearly outside -18 dB to +12 dB relative to 90 dB.
```PCM amplitude levels SHOULD linearly track input SPL changes over at least a 30 dB range from -18 dB to +12 dB re 90 dB SPL at the microphone.```

**Comment by nicolas-f** [comment]
Is 1 dB or 0.5 user input precision is ok. Or the user should be able to give the externally measured value at 0.1 dB ? (Do we switch from seekbar to keyboard value input)

**Comment by Picaut** [comment]
Precision at 0.1 dB is require

**Comment by nicolas-f** [comment]
Is the calibration is done in dB or in dB(A) ?

**Comment by nicolas-f** [comment]
Add gain factor

**Comment by nicolas-f** [comment]
Gui and implementation are done.

![screenshot0](https://cloud.githubusercontent.com/assets/1382241/16444167/13eb38ac-3ddd-11e6-81d3-560525d1e010.png)

**Comment by nicolas-f** [comment]
done 62402fc64733b8ec7b75cb10c6ba2c76b985fcfd
