### ISSUE TITLE
Gps only option

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#61]
Add an option to ignore Network location provider and use GPS coordinates only. useful when measuring only in open outdoor.

**Comment by Picaut** [comment]
Since the accuracy of the positioning from Network is greater than 1.5km, it can be removed.

**Comment by nicolas-f** [comment]
Wifi and Network cannot be differentiated into the application. In NoiseCapture 0.5.X GPS only is used if at least one position is received from GPS during the measurement. So this settings may not be useful for the user.
