### ISSUE TITLE
Synced legend with geoserver

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#65]
In leaflet  use this link
http://onomap-gs.noise-planet.org/geoserver/gwc/service/wms?REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&LAYER=noisecapture:noisecapture_area&legend_options=fontName:Times%20New%20Roman;fontAntiAliasing:true;fontColor:0x000033;fontSize:14;dpi:180&TRANSPARENT=true

![legend](http://onomap-gs.noise-planet.org/geoserver/gwc/service/wms?REQUEST=GetLegendGraphic&VERSION=1.3.0&FORMAT=image/png&LAYER=noisecapture:noisecapture_area&legend_options=fontName:Times%20New%20Roman;fontAntiAliasing:true;fontColor:0x000033;fontSize:14;dpi:180&TRANSPARENT=true)

**Comment by Picaut** [comment]
Done
