### ISSUE TITLE
Frequency band display

### ISSUE THREAD

**Issue by Picaut** [Ifsttar/NoiseCapture#8]
On the display of the histogram (frequency bands), both during Measurement and Results, one should add a visible x-tick (on the x-axis) that correspond to the frequency label.

**Comment by nicolas-f** [comment]
Is this solution possible ?

![noisecapture_horizon](https://cloud.githubusercontent.com/assets/1382241/14742432/7ed96448-089c-11e6-864d-3eb9a4841f20.png)

**Comment by Picaut** [comment]
Not conventional but it can be a relevant solution. You can keep this display. Chance also thé 'Results' display
