### ISSUE TITLE
 Onomap leaflet : disclaimer

### ISSUE THREAD

**Issue by ebocher** [Ifsttar/NoiseCapture#89]
Proposal : 

Disclaimer

The data provided on this site result from a research project. It has no legal force and serves for information purposes only.

Absolutely no accuracy or completeness guarantee is implied or intended.

The authors are not responsible for the direct or indirect consequences of the uses or interpretation of the information provided.

**Comment by ebocher** [comment]
Seems important and urgent @Picaut

**Comment by Picaut** [comment]
Done
