### ISSUE TITLE
Replace maps library on Android device

### ISSUE THREAD

**Issue by nicolas-f** [Ifsttar/NoiseCapture#97]
There is some incompatibility issues with webview and leaflet.
So may be switch to another map library for local and community maps such as:

Mapsforge
osmandroid

**Comment by ebocher** [comment]
What about 

WebSettings webSettings = myWebView.getSettings();
 webSettings.setJavaScriptEnabled(true);

**Comment by gpetit** [comment]
Euh ... wait we have to talk about this.
Please describe your problems in the shared doc.

**Comment by nicolas-f** [comment]
@ebocher This was obviously already done from the first day:

https://github.com/Ifsttar/NoiseCapture/blob/master/app/src/main/java/org/noise_planet/noisecapture/MapActivity.java#L130

**Comment by ebocher** [comment]
ok sorry ;-)
What about http://openlayers.org/
Is this only related to the internal web browser or a bug with a leaflet plugin ?
It was working in the past no ?

**Comment by nicolas-f** [comment]
This is related to the internal browser. Behavior is dependent from android version and manufacturer, and may be some user defined security settings.

Using an internal library would require less bandwidth usage and less cpu usage. However an update on the map layout could only be done through an application update.(we can still use TMS and/or WMS)

**Comment by ebocher** [comment]
Why not just use the current onomap web carto out of android application and offer only a single map in NoiseCapture....

**Comment by nicolas-f** [comment]
@ebocher It would be simpler yes. What do you think @Picaut ?

**Comment by ebocher** [comment]
Because if you choose two different technologies you will have too much job (keep both synchronized).
It's a up to you ;-)

**Comment by gpetit** [comment]
@ebocher not clear for me.
You propose to display only one layer in the NoiseCapture app ? Which one ? The measures made by the user ?

Does it mean that the onomap interface will be removed from the app ? If yes, I agree since it doesn't work on my smartphone.

**Comment by nicolas-f** [comment]
:tropical_drink:  :palm_tree:  Yes I well understood your proposition :smiling_imp:

**Comment by Picaut** [comment]
See #117
